SET STORAGE_NAME=storage_name
SET STORAGE_KEY=storage_key
SET FILESHARE_NAME=fileshare_name
SET MOUNT_POINT=W:

ECHO Mounting fileshare %FILESHARE_NAME% from storage %STORAGE_NAME%
net use %MOUNT_POINT% \\%STORAGE_NAME%.file.core.windows.net\%FILESHARE_NAME% /u:AZURE\%STORAGE_NAME% %STORAGE_KEY% /PERSISTENT:NO